# L3 · BFF Móvil  (contenedor: bffMobile)
bmRouter = component "API Router / Controllers" "Endpoints REST por feature (sync, delta, media). Punto de entrada del contenedor." "FastAPI" "BackendComponent"
bmJwt = component "Middleware de Autenticación" "Valida issuer/audience/expiración del token (segunda validación tras Apigee)." "JWT Middleware (FastAPI)" "BackendComponent,Security"
bmAuthz = component "Servicio de Autorización" "Resuelve GroupToRoleMapping → Role/Permission/Capability." "Python" "BackendComponent,Security"
bmReconciler = component "Motor de Reconciliación" "Regla HU-050: compara timestamp de captura vs. histórico de revocación. Auto-acepta o marca PENDING_REVIEW." "Python — regla HU-050" "BackendComponent"
bmIdempotency = component "Servicio de Idempotencia" "Evita procesar dos veces la misma acción reenviada (dedupe por UUID)." "Python + Redis" "BackendComponent"
bmSequencer = component "Validador de Orden / Secuencia" "Reordena acciones offline por timestamp de captura (no de llegada). Evita que una acción vieja reenviada tarde sobrescriba un estado más reciente." "Python" "BackendComponent"
bmDelta = component "Proveedor de Delta" "Versión + diferencias de catálogos/turnos para descarga incremental (patrón HU-007)." "Python — patrón HU-007" "BackendComponent"
bmUpload = component "Manejador de Subida" "Orquesta la subida de fotos/firma tolerando cortes de red." "GCS Resumable Upload" "BackendComponent"
bmPublisher = component "Publicador de Eventos" "Publica operacion-cerrada y doc-publicacion." "Pub/Sub Publisher" "BackendComponent"
bmSqlClient = component "Cliente Cloud SQL" "Escribe la cola de acciones offline recibidas y el estado de conciliación (PENDIENTE / CONFIRMADO / PENDING_REVIEW) en tablas de Sincronización." "Cloud SQL Python Connector" "BackendComponent"

bmRouter -> bmJwt "Valida" "Llamada in-process (Python)"
bmJwt -> bmAuthz "Resuelve rol" "Llamada in-process (Python)"
bmAuthz -> bmReconciler "Reconcilia" "Llamada in-process (Python)"
bmReconciler -> bmIdempotency "Dedupe" "Llamada in-process (Python)"
bmIdempotency -> bmSequencer "Aplica en orden (timestamp de captura)" "Llamada in-process (Python)"
bmSequencer -> bmReconciler "Secuencia validada" "Llamada in-process (Python)"
bmReconciler -> bmDelta "Catálogos / turnos" "Llamada in-process (Python)"
bmReconciler -> bmUpload "Fotos / firma" "Llamada in-process (Python)"
bmReconciler -> bmPublisher "Al cerrar operación" "Llamada in-process (Python)"
bmUpload -> bmPublisher "Publica eventos de media" "Llamada in-process (Python)"
bmReconciler -> bmSqlClient "Persiste offline_actions_log / PENDING_REVIEW" "Llamada in-process (Python)"
