# L3 · App Móvil  (contenedor: mobileApp)
maNav = component "Navegación" "Pantallas del operario: turnos, checklist, PQDA, firma, historial." "React Navigation" "MobileComponent"
maAuth = component "Módulo de Autenticación" "Flujo OAuth2 Authorization Code + PKCE (solo Entra ID). Token en memoria (no localStorage)." "MSAL" "MobileComponent,Security"
maLocalDb = component "Base de Datos Local" "Réplica funcional: turnos, operaciones, catálogos. Fuente de verdad offline." "WatermelonDB (SQLite)" "MobileComponent,LocalDatabase"
maCrypto = component "Cifrado Local en Reposo" "Cifra la base local. Clave derivada del hardware del dispositivo, no exportable. Protege datos si el dispositivo se pierde o es robado." "SQLCipher + Android Keystore" "MobileComponent,Security"
maSyncEngine = component "Motor de Sincronización" "Cola de escritura local con UUID por acción. Delta pull / push al reconectar. Aplica HU-050." "Cola + UUID (TypeScript)" "MobileComponent"
maSyncState = component "Gestor de Estados de Sincronización" "Por ítem de cola: PENDIENTE → ENVIANDO → CONFIRMADO | CONFLICTO | ERROR. Backoff exponencial (base 5 s, máx 5 min)." "State Machine (local)" "MobileComponent"
maConflict = component "Detector de Conflictos Locales" "Antes de reenviar detecta turno reasignado, recurso bloqueado o catálogo desactualizado. Marca CONFLICTO_LOCAL sin descartar el dato (hecho físico) y espera resolución." "Kotlin/TS — reglas locales" "MobileComponent"
maEvidence = component "Captura de Evidencia" "Fotos PQDA/checklist y firma. Guardado primero en filesystem local." "Cámara + canvas táctil" "MobileComponent"
maSyncTrigger = component "Disparador de Sync" "Detecta reconexión y dispara el Motor de Sincronización." "NetInfo listener" "MobileComponent"
maApiClient = component "Cliente API" "Sube la cola pendiente, descarga delta y sube media con reanudación." "Fetch + Resumable Upload" "MobileComponent"
maZtnaClient = component "Netskope Client (ZTNA)" "Agente ZTNA / perfil de dispositivo. Verifica posture (Intune) antes de habilitar el túnel hacia el BFF Móvil. Sin él no hay salida de red." "Netskope Agent" "MobileComponent,Security"

maNav -> maAuth "Usa" "Llamada in-process (TypeScript)"
maNav -> maLocalDb "Lee / escribe" "Llamada in-process (TypeScript)"
maEvidence -> maLocalDb "Referencia archivo" "Llamada in-process (TypeScript)"
maLocalDb -> maCrypto "Cifra en reposo" "Llamada in-process (TypeScript)"
maLocalDb -> maSyncEngine "Cola pendiente" "Llamada in-process (TypeScript)"
maSyncTrigger -> maSyncEngine "Dispara sync" "Llamada in-process (TypeScript)"
maSyncTrigger -> maEvidence "Notifica conectividad" "Llamada in-process (TypeScript)"
maSyncEngine -> maSyncState "Actualiza estado / backoff exponencial" "Llamada in-process (TypeScript)"
maSyncEngine -> maConflict "Detecta conflicto local" "Llamada in-process (TypeScript)"
maConflict -> maSyncState "Bloquea reintento hasta revisión" "Llamada in-process (TypeScript)"
maSyncEngine -> maApiClient "Al reconectar" "Llamada in-process (TypeScript)"
maApiClient -> maZtnaClient "Sync (online)" "Llamada in-process (TypeScript)"
